services:
  db:
    image: postgres
    restart: always
    container_name: db-url
    volumes:
      - data:/var/lib/postgresql/db
    environment:
      POSTGRES_DB: url
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass "admin"
volumes:
  data:
    external: false
